---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint -d "{extends: default, rules: {line-length: {max: 140, level: warning}}, ignore: .github/workflows/molecule.yml}" .
  ansible-lint --exclude .github
platforms:
  - name: "redis-${image:-docker-centos8-ansible}"
    image: "${namespace:-geerlingguy}/${image:-docker-centos8-ansible}:${tag:-latest}"
    command: ${docker_command:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    tty: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
